#ifndef SERIALPORTDLL3_GLOBAL_H
#define SERIALPORTDLL3_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTDLL3_LIBRARY)
#  define SERIALPORTDLL3_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTDLL3_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTDLL3_GLOBAL_H
